[package]
name = "call"
version = "0.1.0"
authors = ["bingryan <bingryan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "2.33.3"
anyhow = "1.0.36"
log = "0.4.11"

# shell
cmd_lib = "0.12.2"

# console process
console = "0.14.0"
indicatif = "0.15.0"